export { HeroSection } from "./HeroSection"
export { AboutSection } from "./AboutSection"
export { ServicesSection } from "./ServicesSection"
export { ResultsSection } from "./ResultsSection"
export { TestimonialsSection } from "./TestimonialsSection"
export { ContactSection } from "./ContactSection"
